version: '3'

services: 

  laravel:
    image: laravel/test
    container_name: laravel
    networks: 
      - laranet

  nginx:
    image: nginx/test
    container_name: nginx
    networks: 
      - laranet
    ports: 
      - "8080:80"

networks: 
  laranet:
    driver: bridge     